jobs:
  run-job:
    runs-on: ubuntu-latest

    env:
      FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
      APPWRITE_API_KEY: ${{ secrets.APPWRITE_API_KEY }}
      APPWRITE_PROJECT_ID: ${{ secrets.APPWRITE_PROJECT_ID }}
      APPWRITE_END_POINT: ${{ secrets.APPWRITE_END_POINT }}
      APPWRITE_BUCKET_ID: ${{ secrets.APPWRITE_BUCKET_ID }}

    steps:
      - name: Clonar repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Rodar script
        run: python main.py